module.exports = [
    {
        path: false,
        text: "Guide",
        link: false,
        meta: false,
        children: [
            {
                path: "#installation",
                text: "Installation",
                link: "docs/v3/guide/installation.md",
                meta: false,
                children: [],
            },
            {
                path: "#introduction",
                text: "Introduction",
                link: "docs/v3/guide/introduction.md",
                meta: false,
                children: [],
            },
            {
                path: "#elements",
                text: "Elements",
                link: "docs/v3/guide/elements.md",
                meta: false,
                children: [],
            },
            {
                path: "#svg",
                text: "SVG",
                link: "docs/v3/guide/svg.md",
                meta: false,
                children: [],
            },
            {
                path: "#set-children",
                text: "Set Children",
                link: "docs/v3/guide/set-children.md",
                meta: false,
                children: [],
            },
            {
                path: "#update-elements",
                text: "Update elements",
                link: "docs/v3/guide/update-elements.md",
                meta: false,
                children: [],
            },
            {
                path: "#mounting",
                text: "Mounting",
                link: "docs/v3/guide/mounting.md",
                meta: false,
                children: [],
            },
            {
                path: "#components",
                text: "Components",
                link: "docs/v3/guide/components.md",
                meta: false,
                children: [],
            },
            {
                path: "#lists",
                text: "Lists",
                link: "docs/v3/guide/lists.md",
                meta: false,
                children: [],
            },
            {
                path: "#lifecycle",
                text: "Lifecycle",
                link: "docs/v3/guide/lifecycle.md",
                meta: false,
                children: [],
            },
            {
                path: "#place",
                text: "Place",
                link: "docs/v3/guide/place.md",
                meta: false,
                children: [],
            },
            {
                path: "#router",
                text: "Router",
                link: "docs/v3/guide/router.md",
                meta: false,
                children: [],
            },
            {
                path: "#jsx",
                text: "JSX",
                link: "docs/v3/guide/jsx.md",
                meta: false,
                children: [],
            },
        ],
    },
    {
        path: false,
        text: "Misc",
        link: false,
        meta: false,
        children: [
            {
                path: "#api",
                text: "API Reference",
                link: "docs/v3/api/index.md",
                meta: false,
                children: [],
            },
        ],
    },
    {
        path: false,
        text: "Examples",
        link: false,
        meta: false,
        children: [
            {
                path: "#todomvc",
                text: "TodoMVC",
                link: "docs/v3/examples/todomvc.md",
                meta: false,
                children: [],
            },
            {
                path: "#commits",
                text: "GitHub Commits",
                link: "docs/v3/examples/commits.md",
                meta: false,
                children: [],
            },
        ],
    },
];
